model_config:
  model_type: "random_forest"
  params:
    n_estimators: 200
    min_samples_split: 7
    min_samples_leaf: 6
    max_depth: 10
    criterion: "entropy"
    random_state: 101
    class_weight: "balanced"
    n_jobs: -1

training_params:
  scoring: "f1"
  cv: 5
  verbose: 1
  n_jobs: -1
